import {
  ProjectCreatedPayload as ContractsProjectCreatedPayloadSchema,
  ProjectMetaUpdatedPayload as ContractsProjectMetaUpdatedPayloadSchema,
  ProjectQualityPolicyUpdatedPayload as ContractsProjectQualityPolicyUpdatedPayloadSchema,
  ProjectReviewPolicyUpdatedPayload as ContractsProjectReviewPolicyUpdatedPayloadSchema,
  ProjectSharedResourcePayload as ContractsProjectSharedResourcePayloadSchema,
  ProjectSharedResourceDeletedPayload as ContractsProjectSharedResourceDeletedPayloadSchema,
  ResourceLeasesPayload as ContractsResourceLeasesPayloadSchema,
  ArchitectPlanPayload as ContractsArchitectPlanPayloadSchema,
  ProjectDeletedPayload as ContractsProjectDeletedPayloadSchema,
  MissionCreatedPayload as ContractsMissionCreatedPayloadSchema,
  MissionUpdatedPayload as ContractsMissionUpdatedPayloadSchema,
  MissionTaskMembershipPayload as ContractsMissionTaskMembershipPayloadSchema,
  MissionTasksReorderedPayload as ContractsMissionTasksReorderedPayloadSchema,
  MissionDependencyPayload as ContractsMissionDependencyPayloadSchema,
  MissionLifecyclePayload as ContractsMissionLifecyclePayloadSchema,
  MissionIntegrationLinkedPayload as ContractsMissionIntegrationLinkedPayloadSchema,
  MissionRunPayload as ContractsMissionRunPayloadSchema,
  IntegrationCreatedPayload as ContractsIntegrationCreatedPayloadSchema,
  IntegrationActionRequestedPayload as ContractsIntegrationActionRequestedPayloadSchema,
  IntegrationUpdatedPayload as ContractsIntegrationUpdatedPayloadSchema,
  OrchestrationTaskCreatedPayload as ContractsTaskCreatedPayloadSchema,
  OrchestrationTaskAcceptanceCriteriaUpdatedPayload as ContractsTaskAcceptanceCriteriaUpdatedPayloadSchema,
  OrchestrationTaskThreadBoundPayload as ContractsTaskThreadBoundPayloadSchema,
  OrchestrationTaskActivatedPayload as ContractsTaskActivatedPayloadSchema,
  OrchestrationTaskCompletedPayload as ContractsTaskCompletedPayloadSchema,
  OrchestrationTaskCancelledPayload as ContractsTaskCancelledPayloadSchema,
  OrchestrationTaskWorkspacePrepareRequestedPayload as ContractsTaskWorkspacePrepareRequestedPayloadSchema,
  OrchestrationTaskWorkspacePreparationStartedPayload as ContractsTaskWorkspacePreparationStartedPayloadSchema,
  OrchestrationTaskWorkspaceReadyPayload as ContractsTaskWorkspaceReadyPayloadSchema,
  OrchestrationTaskWorkspaceFailedPayload as ContractsTaskWorkspaceFailedPayloadSchema,
  OrchestrationTaskWorkspaceMissingPayload as ContractsTaskWorkspaceMissingPayloadSchema,
  OrchestrationTaskWorkspaceRemoveRequestedPayload as ContractsTaskWorkspaceRemoveRequestedPayloadSchema,
  OrchestrationTaskWorkspaceRemovedPayload as ContractsTaskWorkspaceRemovedPayloadSchema,
  OrchestrationTaskWorkspaceCleanupFailedPayload as ContractsTaskWorkspaceCleanupFailedPayloadSchema,
  OrchestrationTaskOwnershipUpdatedPayload as ContractsTaskOwnershipUpdatedPayloadSchema,
  OrchestrationTaskOwnershipValidationRequestedPayload as ContractsTaskOwnershipValidationRequestedPayloadSchema,
  OrchestrationTaskOwnershipValidatedPayload as ContractsTaskOwnershipValidatedPayloadSchema,
  OrchestrationTaskOwnershipValidationFailedPayload as ContractsTaskOwnershipValidationFailedPayloadSchema,
  OrchestrationTaskResourceRequirementsUpdatedPayload as ContractsTaskResourceRequirementsUpdatedPayloadSchema,
  OrchestrationTaskResourceValidatedPayload as ContractsTaskResourceValidatedPayloadSchema,
  OrchestrationTaskOwnershipRequestPayload as ContractsTaskOwnershipRequestPayloadSchema,
  OrchestrationTaskReviewPrepareRequestedPayload as ContractsTaskReviewPrepareRequestedPayloadSchema,
  OrchestrationTaskReviewPreparedPayload as ContractsTaskReviewPreparedPayloadSchema,
  OrchestrationTaskReviewPrepareFailedPayload as ContractsTaskReviewPrepareFailedPayloadSchema,
  OrchestrationTaskReviewStalePayload as ContractsTaskReviewStalePayloadSchema,
  OrchestrationTaskHandoffUpdatedPayload as ContractsTaskHandoffUpdatedPayloadSchema,
  OrchestrationTaskQualityRunRequestedPayload as ContractsTaskQualityRunRequestedPayloadSchema,
  OrchestrationTaskQualityRunUpdatedPayload as ContractsTaskQualityRunUpdatedPayloadSchema,
  OrchestrationTaskQualityRunCancelRequestedPayload as ContractsTaskQualityRunCancelRequestedPayloadSchema,
  OrchestrationTaskIndependentReviewRequestedPayload as ContractsTaskIndependentReviewRequestedPayloadSchema,
  OrchestrationTaskIndependentReviewStartedPayload as ContractsTaskIndependentReviewStartedPayloadSchema,
  OrchestrationTaskIndependentReviewCompletedPayload as ContractsTaskIndependentReviewCompletedPayloadSchema,
  OrchestrationTaskIndependentReviewFailedPayload as ContractsTaskIndependentReviewFailedPayloadSchema,
  OrchestrationTaskReviewFindingsSentPayload as ContractsTaskReviewFindingsSentPayloadSchema,
  OrchestrationTaskCompletionFreshnessRequestedPayload as ContractsTaskCompletionFreshnessRequestedPayloadSchema,
  OrchestrationTaskRestoreRequestedPayload as ContractsTaskRestoreRequestedPayloadSchema,
  OrchestrationTaskRestoreSnapshotCapturedPayload as ContractsTaskRestoreSnapshotCapturedPayloadSchema,
  OrchestrationTaskRestoredPayload as ContractsTaskRestoredPayloadSchema,
  OrchestrationTaskRestoreUndoRequestedPayload as ContractsTaskRestoreUndoRequestedPayloadSchema,
  OrchestrationTaskRestoreFailedPayload as ContractsTaskRestoreFailedPayloadSchema,
  OrchestrationTaskRestoreUndonePayload as ContractsTaskRestoreUndonePayloadSchema,
  ThreadCreatedPayload as ContractsThreadCreatedPayloadSchema,
  ThreadArchivedPayload as ContractsThreadArchivedPayloadSchema,
  ThreadSettledPayload as ContractsThreadSettledPayloadSchema,
  ThreadMetaUpdatedPayload as ContractsThreadMetaUpdatedPayloadSchema,
  ThreadRuntimeModeSetPayload as ContractsThreadRuntimeModeSetPayloadSchema,
  ThreadInteractionModeSetPayload as ContractsThreadInteractionModeSetPayloadSchema,
  ThreadDeletedPayload as ContractsThreadDeletedPayloadSchema,
  ThreadUnarchivedPayload as ContractsThreadUnarchivedPayloadSchema,
  ThreadUnsettledPayload as ContractsThreadUnsettledPayloadSchema,
  ThreadSnoozedPayload as ContractsThreadSnoozedPayloadSchema,
  ThreadUnsnoozedPayload as ContractsThreadUnsnoozedPayloadSchema,
  ThreadPinnedPayload as ContractsThreadPinnedPayloadSchema,
  ThreadUnpinnedPayload as ContractsThreadUnpinnedPayloadSchema,
  ThreadPinReorderedPayload as ContractsThreadPinReorderedPayloadSchema,
  ThreadMessageSentPayload as ContractsThreadMessageSentPayloadSchema,
  ThreadProposedPlanUpsertedPayload as ContractsThreadProposedPlanUpsertedPayloadSchema,
  ThreadSessionSetPayload as ContractsThreadSessionSetPayloadSchema,
  ThreadTurnDiffCompletedPayload as ContractsThreadTurnDiffCompletedPayloadSchema,
  ThreadRevertedPayload as ContractsThreadRevertedPayloadSchema,
  ThreadActivityAppendedPayload as ContractsThreadActivityAppendedPayloadSchema,
  ThreadTurnStartRequestedPayload as ContractsThreadTurnStartRequestedPayloadSchema,
  ThreadTurnInterruptRequestedPayload as ContractsThreadTurnInterruptRequestedPayloadSchema,
  ThreadApprovalResponseRequestedPayload as ContractsThreadApprovalResponseRequestedPayloadSchema,
  ThreadCheckpointRevertRequestedPayload as ContractsThreadCheckpointRevertRequestedPayloadSchema,
  ThreadSessionStopRequestedPayload as ContractsThreadSessionStopRequestedPayloadSchema,
} from "@t3tools/contracts";

// Server-internal alias surface, backed by contract schemas as the source of truth.
export const ProjectCreatedPayload = ContractsProjectCreatedPayloadSchema;
export const ProjectMetaUpdatedPayload = ContractsProjectMetaUpdatedPayloadSchema;
export const ProjectQualityPolicyUpdatedPayload = ContractsProjectQualityPolicyUpdatedPayloadSchema;
export const ProjectReviewPolicyUpdatedPayload = ContractsProjectReviewPolicyUpdatedPayloadSchema;
export const ProjectSharedResourcePayload = ContractsProjectSharedResourcePayloadSchema;
export const ProjectSharedResourceDeletedPayload =
  ContractsProjectSharedResourceDeletedPayloadSchema;
export const ResourceLeasesPayload = ContractsResourceLeasesPayloadSchema;
export const ArchitectPlanPayload = ContractsArchitectPlanPayloadSchema;
export const ProjectDeletedPayload = ContractsProjectDeletedPayloadSchema;
export const MissionCreatedPayload = ContractsMissionCreatedPayloadSchema;
export const MissionUpdatedPayload = ContractsMissionUpdatedPayloadSchema;
export const MissionTaskMembershipPayload = ContractsMissionTaskMembershipPayloadSchema;
export const MissionTasksReorderedPayload = ContractsMissionTasksReorderedPayloadSchema;
export const MissionDependencyPayload = ContractsMissionDependencyPayloadSchema;
export const MissionLifecyclePayload = ContractsMissionLifecyclePayloadSchema;
export const MissionIntegrationLinkedPayload = ContractsMissionIntegrationLinkedPayloadSchema;
export const MissionRunPayload = ContractsMissionRunPayloadSchema;
export const IntegrationCreatedPayload = ContractsIntegrationCreatedPayloadSchema;
export const IntegrationActionRequestedPayload = ContractsIntegrationActionRequestedPayloadSchema;
export const IntegrationUpdatedPayload = ContractsIntegrationUpdatedPayloadSchema;

export const TaskCreatedPayload = ContractsTaskCreatedPayloadSchema;
export const TaskAcceptanceCriteriaUpdatedPayload =
  ContractsTaskAcceptanceCriteriaUpdatedPayloadSchema;
export const TaskThreadBoundPayload = ContractsTaskThreadBoundPayloadSchema;
export const TaskActivatedPayload = ContractsTaskActivatedPayloadSchema;
export const TaskCompletedPayload = ContractsTaskCompletedPayloadSchema;
export const TaskCancelledPayload = ContractsTaskCancelledPayloadSchema;
export const TaskWorkspacePrepareRequestedPayload =
  ContractsTaskWorkspacePrepareRequestedPayloadSchema;
export const TaskWorkspacePreparationStartedPayload =
  ContractsTaskWorkspacePreparationStartedPayloadSchema;
export const TaskWorkspaceReadyPayload = ContractsTaskWorkspaceReadyPayloadSchema;
export const TaskWorkspaceFailedPayload = ContractsTaskWorkspaceFailedPayloadSchema;
export const TaskWorkspaceMissingPayload = ContractsTaskWorkspaceMissingPayloadSchema;
export const TaskWorkspaceRemoveRequestedPayload =
  ContractsTaskWorkspaceRemoveRequestedPayloadSchema;
export const TaskWorkspaceRemovedPayload = ContractsTaskWorkspaceRemovedPayloadSchema;
export const TaskWorkspaceCleanupFailedPayload = ContractsTaskWorkspaceCleanupFailedPayloadSchema;
export const TaskOwnershipUpdatedPayload = ContractsTaskOwnershipUpdatedPayloadSchema;
export const TaskOwnershipValidationRequestedPayload =
  ContractsTaskOwnershipValidationRequestedPayloadSchema;
export const TaskOwnershipValidatedPayload = ContractsTaskOwnershipValidatedPayloadSchema;
export const TaskOwnershipValidationFailedPayload =
  ContractsTaskOwnershipValidationFailedPayloadSchema;
export const TaskResourceRequirementsUpdatedPayload =
  ContractsTaskResourceRequirementsUpdatedPayloadSchema;
export const TaskResourceValidatedPayload = ContractsTaskResourceValidatedPayloadSchema;
export const TaskOwnershipRequestPayload = ContractsTaskOwnershipRequestPayloadSchema;
export const TaskReviewPrepareRequestedPayload = ContractsTaskReviewPrepareRequestedPayloadSchema;
export const TaskReviewPreparedPayload = ContractsTaskReviewPreparedPayloadSchema;
export const TaskReviewPrepareFailedPayload = ContractsTaskReviewPrepareFailedPayloadSchema;
export const TaskReviewStalePayload = ContractsTaskReviewStalePayloadSchema;
export const TaskHandoffUpdatedPayload = ContractsTaskHandoffUpdatedPayloadSchema;
export const TaskQualityRunRequestedPayload = ContractsTaskQualityRunRequestedPayloadSchema;
export const TaskQualityRunUpdatedPayload = ContractsTaskQualityRunUpdatedPayloadSchema;
export const TaskQualityRunCancelRequestedPayload =
  ContractsTaskQualityRunCancelRequestedPayloadSchema;
export const TaskIndependentReviewRequestedPayload =
  ContractsTaskIndependentReviewRequestedPayloadSchema;
export const TaskIndependentReviewStartedPayload =
  ContractsTaskIndependentReviewStartedPayloadSchema;
export const TaskIndependentReviewCompletedPayload =
  ContractsTaskIndependentReviewCompletedPayloadSchema;
export const TaskIndependentReviewFailedPayload = ContractsTaskIndependentReviewFailedPayloadSchema;
export const TaskReviewFindingsSentPayload = ContractsTaskReviewFindingsSentPayloadSchema;
export const TaskCompletionFreshnessRequestedPayload =
  ContractsTaskCompletionFreshnessRequestedPayloadSchema;
export const TaskRestoreRequestedPayload = ContractsTaskRestoreRequestedPayloadSchema;
export const TaskRestoreSnapshotCapturedPayload = ContractsTaskRestoreSnapshotCapturedPayloadSchema;
export const TaskRestoredPayload = ContractsTaskRestoredPayloadSchema;
export const TaskRestoreUndoRequestedPayload = ContractsTaskRestoreUndoRequestedPayloadSchema;
export const TaskRestoreFailedPayload = ContractsTaskRestoreFailedPayloadSchema;
export const TaskRestoreUndonePayload = ContractsTaskRestoreUndonePayloadSchema;

export const ThreadCreatedPayload = ContractsThreadCreatedPayloadSchema;
export const ThreadArchivedPayload = ContractsThreadArchivedPayloadSchema;
export const ThreadSettledPayload = ContractsThreadSettledPayloadSchema;
export const ThreadMetaUpdatedPayload = ContractsThreadMetaUpdatedPayloadSchema;
export const ThreadRuntimeModeSetPayload = ContractsThreadRuntimeModeSetPayloadSchema;
export const ThreadInteractionModeSetPayload = ContractsThreadInteractionModeSetPayloadSchema;
export const ThreadDeletedPayload = ContractsThreadDeletedPayloadSchema;
export const ThreadUnarchivedPayload = ContractsThreadUnarchivedPayloadSchema;
export const ThreadUnsettledPayload = ContractsThreadUnsettledPayloadSchema;
export const ThreadSnoozedPayload = ContractsThreadSnoozedPayloadSchema;
export const ThreadUnsnoozedPayload = ContractsThreadUnsnoozedPayloadSchema;
export const ThreadPinnedPayload = ContractsThreadPinnedPayloadSchema;
export const ThreadUnpinnedPayload = ContractsThreadUnpinnedPayloadSchema;
export const ThreadPinReorderedPayload = ContractsThreadPinReorderedPayloadSchema;

export const MessageSentPayloadSchema = ContractsThreadMessageSentPayloadSchema;
export const ThreadProposedPlanUpsertedPayload = ContractsThreadProposedPlanUpsertedPayloadSchema;
export const ThreadSessionSetPayload = ContractsThreadSessionSetPayloadSchema;
export const ThreadTurnDiffCompletedPayload = ContractsThreadTurnDiffCompletedPayloadSchema;
export const ThreadRevertedPayload = ContractsThreadRevertedPayloadSchema;
export const ThreadActivityAppendedPayload = ContractsThreadActivityAppendedPayloadSchema;

export const ThreadTurnStartRequestedPayload = ContractsThreadTurnStartRequestedPayloadSchema;
export const ThreadTurnInterruptRequestedPayload =
  ContractsThreadTurnInterruptRequestedPayloadSchema;
export const ThreadApprovalResponseRequestedPayload =
  ContractsThreadApprovalResponseRequestedPayloadSchema;
export const ThreadCheckpointRevertRequestedPayload =
  ContractsThreadCheckpointRevertRequestedPayloadSchema;
export const ThreadSessionStopRequestedPayload = ContractsThreadSessionStopRequestedPayloadSchema;
